# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy the rest of the application files
COPY . ./

# Expose any ports if necessary (not required for stdio-based MCP)

# Run the MCP server
CMD ["node", "simple-repl-server.js"]
