/**
 * Updated test file for MCP compatibility
 * Generated by update-test-expectations.js
 */

export default [
  {
    "name": "Simple addition",
    "code": "return 2 + 2",
    "expected": "4"
  },
  {
    "name": "String concatenation",
    "code": "return \"Hello, \" + \"World!\"",
    "expected": "Hello, World!"
  },
  {
    "name": "Object declaration",
    "code": "return { a: 1, b: 2 }",
    "expected": "{ a: 1, b: 2 }"
  },
  {
    "name": "Array operations",
    "code": "const arr = [1, 2, 3]; return arr.map(x => x * 2)",
    "expected": "[ 2, 4, 6 ]"
  },
  {
    "name": "Console output",
    "code": "console.log(\"Testing console output\"); return \"done\"",
    "expected": "Testing console output"
  },
  {
    "name": "Multiple statements",
    "code": "let x = 10; x = x * 2; return x",
    "expected": "20"
  },
  {
    "name": "Empty return",
    "code": "return",
    "expected": "undefined"
  },
  {
    "name": "No return statement",
    "code": "const x = 42",
    "expected": "undefined"
  }
];