/**
 * Updated test file for MCP compatibility
 * Generated by update-test-expectations.js
 */

export default [
  {
    "name": "Console log",
    "code": "console.log(\"Testing console output\"); return \"Done\";",
    "expected": ({ logs }) => logs && logs.some(log => log.includes("Testing console output"))
  },
  {
    "name": "Multiple console methods",
    "code": "console.log(\"Log\"); console.error(\"Error\"); console.warn(\"Warning\"); return \"Multiple logs\";",
    "expected": ({ logs }) => {
      if (!logs) return false;
      return logs.some(log => log.includes("Log")) &&
             logs.some(log => log.includes("Error")) &&
             logs.some(log => log.includes("Warning"));
    }
  },
  {
    "name": "Console with complex objects",
    "code": "console.log({ a: 1, b: { c: 2 }}); return \"Object logged\";",
    "expected": ({ logs }) => {
      if (!logs) return false;
      return logs.some(log => 
        log.includes("a") && 
        log.includes("1") && 
        log.includes("b") && 
        log.includes("c") && 
        log.includes("2")
      );
    }
  }
];