/**
 * Updated test file for MCP compatibility
 * Generated by update-test-expectations.js
 */

export default [
  {
    "name": "Console log",
    "code": "console.log(\"Testing console output\"); return \"Done\";",
    "expectedConsoleOutput": "Testing console output",
    "expectedResult": "Done",
    "expected": "Testing console output"
  },
  {
    "name": "Multiple console methods",
    "code": "console.log(\"Log\"); console.error(\"Error\"); console.warn(\"Warning\"); return \"Multiple logs\";",
    "expectedConsoleOutput": [
      "Log",
      "Error",
      "Warning"
    ],
    "expectedResult": "Multiple logs",
    "expected": "Log\nError\nWarning"
  },
  {
    "name": "Console with complex objects",
    "code": "console.log({ a: 1, b: { c: 2 }}); return \"Object logged\";",
    "expectedConsoleOutput": "a: 1",
    "expectedResult": "Object logged",
    "expected": "{ a: 1, b: { c: 2 } }"
  }
];