/**
 * Updated test file for MCP compatibility
 * Generated by update-test-expectations.js
 */

export default [
  {
    "name": "Object destructuring",
    "code": "const { a, b } = { a: 1, b: 2 }; return a + b;",
    "expectedResult": "3",
    "expected": "3"
  },
  {
    "name": "Array spread operator",
    "code": "const arr1 = [1, 2]; const arr2 = [3, 4]; return [...arr1, ...arr2];",
    "expectedResult": "1, 2, 3, 4",
    "expected": ({ returnValue }) => {
      if (typeof returnValue === 'string') {
        // Normalize the string by removing whitespace
        const normalized = returnValue.replace(/\s+/g, '');
        return normalized === '[1,2,3,4]';
      }
      return false;
    }
  },
  {
    "name": "Template literals",
    "code": "const name = \"World\"; return `Hello, ${name}!`;",
    "expectedResult": "Hello, World!",
    "expected": "Hello, World!"
  }
];