/**
 * Updated test file for MCP compatibility
 * Generated by update-test-expectations.js
 */

export default [
  {
    "name": "Empty return",
    "code": "return;",
    "expectedResult": "undefined",
    "expected": "undefined"
  },
  {
    "name": "No return statement",
    "code": "const x = 42;",
    "expectedResult": "undefined",
    "expected": "undefined"
  },
  {
    "name": "Large output handling",
    "code": "return Array(100).fill(0).map((_, i) => i);",
    "expectedResult": "0",
    "expected": "[\n   0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,\n  12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,\n  24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,\n  36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,\n  48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,\n  60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,\n  72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,\n  84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,\n  96, 97, 98, 99\n]"
  },
  {
    "name": "Special characters",
    "code": "return \"Special chars: \\n\\t\\r\\\"\\\"\";",
    "expectedResult": "Special chars:",
    "expected": "Special chars: \n\t\r\"\""
  }
];