/**
 * Updated test file for MCP compatibility
 * Generated by update-test-expectations.js
 */

export default [
  {
    "name": "Simple addition",
    "code": "return 2 + 2",
    "expected": "4"
  },
  {
    "name": "Console output",
    "code": "console.log(\"Testing MCP output\"); return \"done\"",
    "expected": "done"
  }
];