/**
 * Updated test file for MCP compatibility
 * Generated by update-test-expectations.js
 */

export default [
  {
    "name": "JSON parsing",
    "code": "return JSON.parse('{\"key\":\"value\"}');",
    "expectedResult": "key",
    "expected": "{ key: 'value' }"
  }
];