/**
 * Updated test file for MCP compatibility
 * Generated by update-test-expectations.js
 */

export default [
  {
    "name": "Access process.env",
    "code": "return typeof process.env === \"object\";",
    "expectedResult": "true",
    "expected": "true"
  },
  {
    "name": "Process env properties",
    "code": "const keys = Object.keys(process.env); return keys.length > 0;",
    "expectedResult": "true",
    "expected": "true"
  },
  {
    "name": "Set environment variable",
    "code": "process.env.TEST_VAR = \"test value\"; return process.env.TEST_VAR;",
    "expectedResult": "test value",
    "expected": "test value"
  },
  {
    "name": "Delete environment variable",
    "code": "process.env.TO_DELETE = \"temp\"; delete process.env.TO_DELETE; return process.env.TO_DELETE === undefined;",
    "expectedResult": "true",
    "expected": "true"
  },
  {
    "name": "Process.cwd",
    "code": "return typeof process.cwd() === \"string\";",
    "expectedResult": "true",
    "expected": "true"
  },
  {
    "name": "Process.hrtime",
    "code": "const hrtime = process.hrtime(); return Array.isArray(hrtime) && hrtime.length === 2;",
    "expectedResult": "true",
    "expected": "true"
  },
  {
    "name": "Process.hrtime.bigint",
    "code": "try { const time = process.hrtime.bigint(); return typeof time === \"bigint\"; } catch (e) { return \"Not supported\"; }",
    "expectedResult": "true",
    "expected": "true"
  },
  {
    "name": "Process.memoryUsage",
    "code": "const mem = process.memoryUsage(); return mem.hasOwnProperty(\"heapUsed\");",
    "expectedResult": "true",
    "expected": "process.memoryUsage is not a function\n    at evalmachine.<anonymous>:3:29\n    at evalmachine.<anonymous>:7:7\n    at Script.runInContext (node:vm:149:12)\n    at file:///C:/Users/user/Documents/Cline/MCP/simple-repl/simple-repl-server.js:128:38\n    at executeCode (file:///C:/Users/user/Documents/Cline/MCP/simple-repl/simple-repl-server.js:133:9)\n    at processRequest (file:///C:/Users/user/Documents/Cline/MCP/simple-repl/simple-repl-server.js:273:28)\n    at Socket.<anonymous> (file:///C:/Users/user/Documents/Cline/MCP/simple-repl/simple-repl-server.js:324:32)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)"
  },
  {
    "name": "Process.nextTick",
    "code": "return new Promise(resolve => { process.nextTick(() => resolve(\"nextTick executed\")); });",
    "expectedResult": "nextTick executed",
    "expected": "nextTick executed"
  }
];